export const skillGroups = [
  {
    id: 'tools',
    label: 'Programming & Tools',
    items: [
      'Angular',
      'Azure',
      'Databricks',
      'Docker',
      'FastAPI',
      'Flask',
      'Git/GitHub',
      'GitHub Copilot',
      'JavaScript',
      'LangChain/LangGraph',
      'LLMs',
      'MongoDB',
      'Next.js',
      'Node.js',
      'Postgres',
      'Python',
      'RAG',
      'React.js',
      'REST',
      'Snowflake',
      'SQL',
      'TypeScript',
    ],
  },
  {
    id: 'ml',
    label: 'ML/DL Libraries',
    items: [
      'BeautifulSoup',
      'NumPy',
      'OpenCV',
      'Pandas',
      'PySpark',
      'PyTorch',
      'SciPy',
      'Selenium',
      'Scikit-learn',
      'TensorFlow',
    ],
  },
];
